In [1]:
import yfinance as yf

In [2]:
novo = yf.Ticker("NOVO-B.CO")

In [3]:
novo.quarterly_income_stmt

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.204,0.204815,0.199,0.199,0.199
Normalized EBITDA,36906000000.0,28511000000.0,32756000000.0,26712000000.0,27578000000.0
Net Income From Continuing Operation Net Minority Interest,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Reconciled Depreciation,2914000000.0,2992000000.0,2525000000.0,2177000000.0,1719000000.0
Reconciled Cost Of Revenue,9916000000.0,10014000000.0,9713000000.0,7856000000.0,8182000000.0
EBITDA,36906000000.0,28511000000.0,32756000000.0,26712000000.0,27578000000.0
EBIT,33992000000.0,25519000000.0,30231000000.0,24535000000.0,25859000000.0
Net Interest Income,72000000.0,-916000000.0,1150000000.0,366000000.0,-270000000.0
Interest Expense,2074000000.0,-2101000000.0,2168000000.0,281000000.0,1122000000.0
Interest Income,2146000000.0,-2820000000.0,3318000000.0,647000000.0,852000000.0
Normalized Income,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Net Income From Continuing And Discontinued Operation,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Total Expenses,33503000000.0,39097000000.0,31818000000.0,30412000000.0,28360000000.0
Total Operating Income As Reported,31846000000.0,26766000000.0,26913000000.0,23888000000.0,25007000000.0
Diluted Average Shares,4470500000.0,NaN,4489000000.0,4502600000.0,4513200000.0
Basic Average Shares,4459600000.0,NaN,4476900000.0,4490400000.0,4499200000.0
Diluted EPS,5.68,NaN,5.0,4.315,4.39
Basic EPS,5.7,NaN,5.02,4.325,4.4
Diluted NI Availto Com Stockholders,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Net Income Common Stockholders,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Net Income,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Net Income Including Noncontrolling Interests,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Net Income Continuous Operations,25407000000.0,21963000000.0,22478000000.0,19428000000.0,19814000000.0
Tax Provision,6511000000.0,5657000000.0,5585000000.0,4826000000.0,4923000000.0
Pretax Income,31918000000.0,27620000000.0,28063000000.0,24254000000.0,24737000000.0
Net Non Operating Interest Income Expense,72000000.0,-916000000.0,1150000000.0,366000000.0,-270000000.0
Interest Expense Non Operating,2074000000.0,-2101000000.0,2168000000.0,281000000.0,1122000000.0
Interest Income Non Operating,2146000000.0,-2820000000.0,3318000000.0,647000000.0,852000000.0
Operating Income,31846000000.0,26766000000.0,26913000000.0,23888000000.0,25007000000.0
Operating Expense,23587000000.0,29083000000.0,22105000000.0,22556000000.0,20178000000.0
Other Operating Expenses,568000000.0,-3000000.0,-98000000.0,15000000.0,-33000000.0
Research And Development,8606000000.0,10460000000.0,8128000000.0,7127000000.0,6728000000.0
Selling General And Administration,14413000000.0,18626000000.0,14075000000.0,15414000000.0,13483000000.0
Selling And Marketing Expense,13256000000.0,17170000000.0,12819000000.0,14342000000.0,12412000000.0
General And Administrative Expense,1157000000.0,1456000000.0,1256000000.0,1072000000.0,1071000000.0
Other Gand A,1157000000.0,1456000000.0,1256000000.0,1072000000.0,1071000000.0
Gross Profit,55433000000.0,55849000000.0,49018000000.0,46444000000.0,45185000000.0
Cost Of Revenue,9916000000.0,10014000000.0,9713000000.0,7856000000.0,8182000000.0
Total Revenue,65349000000.0,65863000000.0,58731000000.0,54300000000.0,53367000000.0
Operating Revenue,65349000000.0,442247000000.0,58731000000.0,54300000000.0,53367000000.0

In [4]:
novo.info

{'address1': 'Novo Alle 1',
 'city': 'Bagsvaerd',
 'zip': '2880',
 'country': 'Denmark',
 'phone': '45 44 44 88 88',
 'website': 'https://www.novonordisk.com',
 'industry': 'Biotechnology',
 'industryKey': 'biotechnology',
 'industryDisp': 'Biotechnology',
 'sector': 'Healthcare',
 'sectorKey': 'healthcare',
 'sectorDisp': 'Healthcare',
 'longBusinessSummary': 'Novo Nordisk A/S, together with its subsidiaries, engages in the research and development, manufacture, and distribution of pharmaceutical products in Europe, the Middle East, Africa, Mainland China, Hong Kong, Taiwan, North America, and internationally. It operates in two segments, Diabetes and Obesity Care, and Rare Disease. The Diabetes and Obesity care segment provides products for diabetes, obesity, cardiovascular, and other emerging therapy areas. The Rare Disease segment offers products in the areas of rare blood disorders, rare endocrine disorders, and hormone replacement therapy. The company also provides insulin pens, growth hormone pens, and injection needles. In addition, it offers smart solutions for diabetes treatment, such as smart insulin pens and Dose Check, an insulin dose guidance application. The company has a collaboration agreement with Aspen Pharmaceuticals to produce insulin products. Novo Nordisk A/S was founded in 1923 and is headquartered in Bagsvaerd, Denmark.',
 'fullTimeEmployees': 66015,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Lars Fruergaard Jorgensen',
   'age': 57,
   'title': 'President, CEO & Member of Management Board',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'totalPay': 32300000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Karsten Munk Knudsen',
   'age': 52,
   'title': 'Executive VP, CFO & Member of the Management Board',
   'yearBorn': 1971,
   'fiscalYear': 2022,
   'totalPay': 12800000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Henrik Ehlers Wulff',
   'age': 53,
   'title': 'Executive VP of Product Supply, Quality & IT and Member of the Management Board',
   'yearBorn': 1970,
   'fiscalYear': 2022,
   'totalPay': 12900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Camilla  Sylvest',
   'age': 51,
   'title': 'Executive VP of Commercial Strategy & Corporate Affairs and Member of the Management Board',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 12600000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Martin Holst Lange',
   'age': 53,
   'title': 'Executive VP of Development & Member of the Management Board',
   'yearBorn': 1970,
   'fiscalYear': 2022,
   'totalPay': 12200000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Marcus  Schindler Ph.D.',
   'age': 57,
   'title': 'EVP of Research & Early Development, Chief Scientific Officer & Member of the Management Board',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'totalPay': 12200000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Maziar Mike Doustdar',
   'age': 53,
   'title': 'Executive VP of International Operations & Member of the Management Board',
   'yearBorn': 1970,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Douglas J. Langa',
   'age': 57,
   'title': 'Executive VP of North America Operations & Member of Management Board',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ludovic  Helfgott',
   'age': 49,
   'title': 'Executive VP, Head of Rare Disease & Member of Management Board',
   'yearBorn': 1974,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Tania  Sabroe',
   'age': 46,
   'title': 'Executive VP of Global People & Organisation and Member of Management Board',
   'yearBorn': 1977,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 3,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 9,
 'overallRisk': 1,
 'governanceEpochDate': 1719792000,
 'compensationAsOfEpochDate': 1672444800,
 'irWebsite': 'http://www.novonordisk.com/investors/default.asp',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 974.0,
 'open': 977.8,
 'dayLow': 971.0,
 'dayHigh': 984.4,
 'regularMarketPreviousClose': 974.0,
 'regularMarketOpen': 977.8,
 'regularMarketDayLow': 971.0,
 'regularMarketDayHigh': 984.4,
 'dividendRate': 12.8,
 'dividendYield': 0.013099999,
 'exDividendDate': 1711065600,
 'payoutRatio': 0.4721,
 'fiveYearAvgDividendYield': 1.55,
 'beta': 0.151,
 'trailingPE': 49.345745,
 'forwardPE': 33.395775,
 'volume': 570457,
 'regularMarketVolume': 570457,
 'averageVolume': 2449574,
 'averageVolume10days': 2182643,
 'averageDailyVolume10Day': 2182643,
 'bid': 980.3,
 'ask': 980.3,
 'marketCap': 4366725545984,
 'fiftyTwoWeekLow': 504.4,
 'fiftyTwoWeekHigh': 1033.2,
 'priceToSalesTrailing12Months': 17.87861,
 'fiftyDayAverage': 940.54,
 'twoHundredDayAverage': 803.4635,
 'trailingAnnualDividendRate': 9.4,
 'trailingAnnualDividendYield': 0.009650923,
 'currency': 'DKK',
 'enterpriseValue': 4361275310080,
 'profitMargins': 0.36551997,
 'floatShares': 3186339604,
 'sharesOutstanding': 3378700032,
 'heldPercentInsiders': 0.06058,
 'heldPercentInstitutions': 0.3798,
 'impliedSharesOutstanding': 4573259776,
 'bookValue': 22.179,
 'priceToBook': 44.208485,
 'lastFiscalYearEnd': 1703980800,
 'nextFiscalYearEnd': 1735603200,
 'mostRecentQuarter': 1711843200,
 'earningsQuarterlyGrowth': 0.282,
 'netIncomeToCommon': 89275998208,
 'trailingEps': 19.87,
 'forwardEps': 29.36,
 'pegRatio': 1.54,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1694563200,
 'enterpriseToRevenue': 17.856,
 'enterpriseToEbitda': 37.008,
 '52WeekChange': 0.8346205,
 'SandP52WeekChange': 0.26253593,
 'lastDividendValue': 6.4,
 'lastDividendDate': 1711065600,
 'exchange': 'CPH',
 'quoteType': 'EQUITY',
 'symbol': 'NOVO-B.CO',
 'underlyingSymbol': 'NOVO-B.CO',
 'shortName': 'Novo Nordisk B A/S',
 'longName': 'Novo Nordisk A/S',
 'firstTradeDateEpochUtc': 978768000,
 'timeZoneFullName': 'Europe/Copenhagen',
 'timeZoneShortName': 'CEST',
 'uuid': 'dc21647a-ac72-3024-917d-9a82cdc63d38',
 'messageBoardId': 'finmb_323452',
 'gmtOffSetMilliseconds': 7200000,
 'currentPrice': 980.5,
 'targetHighPrice': 1200.0,
 'targetLowPrice': 560.0,
 'targetMeanPrice': 952.54,
 'targetMedianPrice': 995.0,
 'recommendationMean': 2.3,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 26,
 'totalCash': 9303000064,
 'totalCashPerShare': 2.086,
 'ebitda': 117846999040,
 'totalDebt': 26928001024,
 'quickRatio': 0.489,
 'currentRatio': 0.703,
 'totalRevenue': 244243005440,
 'debtToEquity': 27.224,
 'revenuePerShare': 54.605,
 'returnOnAssets': 0.25236,
 'returnOnEquity': 0.9987,
 'freeCashflow': 40243126272,
 'operatingCashflow': 93408002048,
 'earningsGrowth': 0.294,
 'revenueGrowth': 0.225,
 'grossMargins': 0.84647006,
 'ebitdaMargins': 0.4825,
 'operatingMargins': 0.48731998,
 'financialCurrency': 'DKK',
 'trailingPegRatio': 2.4704}

In [5]:
novo.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-10 00:00:00+02:00,979.000000,991.299988,979.000000,988.400024,1957347,0.0,0.0
2024-06-11 00:00:00+02:00,992.000000,997.400024,979.200012,982.000000,2681156,0.0,0.0
2024-06-12 00:00:00+02:00,984.000000,993.500000,981.799988,989.599976,1875906,0.0,0.0
2024-06-13 00:00:00+02:00,991.200012,993.099976,979.700012,979.700012,1848673,0.0,0.0
2024-06-14 00:00:00+02:00,984.700012,996.900024,977.000000,991.000000,2230435,0.0,0.0
2024-06-17 00:00:00+02:00,991.000000,995.400024,980.500000,980.500000,2299629,0.0,0.0
2024-06-18 00:00:00+02:00,980.000000,983.700012,972.799988,981.200012,2019930,0.0,0.0
2024-06-19 00:00:00+02:00,973.700012,984.900024,972.400024,984.200012,1225696,0.0,0.0
2024-06-20 00:00:00+02:00,985.000000,993.799988,979.599976,993.799988,1892064,0.0,0.0
2024-06-21 00:00:00+02:00,983.200012,993.599976,978.599976,987.900024,4624522,0.0,0.0
2024-06-24 00:00:00+02:00,988.000000,995.799988,982.000000,988.400024,1646238,0.0,0.0
2024-06-25 00:00:00+02:00,990.000000,1028.000000,987.299988,1028.000000,3196908,0.0,0.0
2024-06-26 00:00:00+02:00,1011.200012,1033.199951,1003.400024,1007.000000,2763630,0.0,0.0
2024-06-27 00:00:00+02:00,999.000000,1010.799988,995.500000,1002.599976,1939839,0.0,0.0
2024-06-28 00:00:00+02:00,1015.400024,1015.400024,998.599976,1005.599976,1801075,0.0,0.0
2024-07-01 00:00:00+02:00,1017.400024,1017.400024,988.200012,1004.599976,1858642,0.0,0.0
2024-07-02 00:00:00+02:00,1007.000000,1013.400024,965.599976,993.500000,2905878,0.0,0.0
2024-07-03 00:00:00+02:00,988.799988,989.799988,967.500000,967.500000,2411571,0.0,0.0
2024-07-04 00:00:00+02:00,951.099976,976.200012,947.500000,970.000000,1603803,0.0,0.0
2024-07-05 00:00:00+02:00,980.000000,980.599976,967.000000,974.000000,1698852,0.0,0.0
2024-07-08 00:00:00+02:00,977.799988,984.400024,971.000000,980.500000,570457,0.0,0.0